#!/usr/bin/env python2

from chininux import *

try:
    query = sys.argv[1]
except:
    print "Usage: %s <IP address>" % sys.argv[0]
    sys.exit(1)

ad = AddressDirectory(GIURLS)
ad.start()
for r in ad.search(query):
    print r

